application: letsbrewlist
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css

- url: /update/.*
  script: letsbrewlist.app
  login: admin
  auth_fail_action: redirect

- url: /.*
  script: letsbrewlist.app

libraries:
- name: jinja2
  version: latest
- name: django
  version: latest

builtins:
- deferred: on
